on:
  push:
    branches:
      - test

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        uses: paulhatch/semantic-version@v5.1.0
        with:
          tag_prefix: 'v'
          major_pattern: '(MAJOR)'
          minor_pattern: '(MINOR)'