on:
  push:
    branches:
      - test

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the last tag name
        run: echo "PREVIOUS_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Get new version
        uses: paulhatch/semantic-version@v5.1.0
        id: version
        with:
          tag_prefix: 'v'
          major_pattern: '(MAJOR)'
          minor_pattern: '(MINOR)'

      - name: Get the changes since previous tag
        run: |
          changes=$(gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/vchiranjeeviako/testing/releases/generate-notes \
          -f tag_name='${{ steps.version.outputs.version_tag }}' \
          -f target_commitish='test' \
          -f previous_tag_name='${{ env.PREVIOUS_TAG }}')
          echo $changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}